name: Build FFmpeg for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-yasm
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-zlib
            zip

      - name: Download FFmpeg source code
        run: |
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg
          cd ffmpeg

      - name: Configure FFmpeg
        shell: msys2 {0}
        run: |
          cd ffmpeg
          ./configure --disable-everything \
            --enable-ffmpeg \
            --enable-avformat \
            --enable-avcodec \
            --enable-avutil \
            --enable-decoder=srt \
            --enable-decoder=webvtt \
            --enable-decoder=ass \
            --enable-demuxer=mov \
            --enable-protocol=file \
            --enable-muxer=srt

      - name: Build and install FFmpeg
        shell: msys2 {0}
        run: |
          cd ffmpeg
          make
          make install

      - name: Package FFmpeg
        shell: msys2 {0}
        run: |
          mkdir -p /usr/local/bin/ffmpeg
          mv /usr/local/bin/ffmpeg.exe /usr/local/bin/ffprobe.exe /usr/local/bin/ffmpeg/


      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg-windows
          path: D:\a\_temp\msys64\usr\local\bin\ffmpeg