name: Build FFmpeg for Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            base-devel
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-yasm
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-zlib
            mingw-w64-x86_64-iconv
            zip
            nasm
            mingw-w64-x86_64-cmake
            git

      - name: Download FFmpeg source code
        run: |
          git clone https://git.ffmpeg.org/ffmpeg.git ffmpeg

      - name: Clone & Build whisper.cpp
        shell: msys2 {0}
        run: |
          set -euo pipefail
          PREFIX="/usr/local"
          git clone https://github.com/ggerganov/whisper.cpp.git
          cd whisper.cpp
          mkdir -p build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX="${PREFIX}" \
                -DWHISPER_BUILD_TESTS=OFF \
                -DWHISPER_BUILD_EXAMPLES=OFF \
                -DWHISPER_BUILD_SHARED_LIB=OFF \
                -DGGML_SHARED=OFF \
                -DWHISPER_NO_ACCELERATE=ON \
                -DBUILD_SHARED_LIBS=OFF \
                ..
          cmake --build . --config Release -j $(nproc)
          cmake --install .
          
          # 验证安装 - 查看实际安装的库文件
          echo "=== 查看安装的静态库 ==="
          find "${PREFIX}/lib" -name "*.a" | sort || true
          
          echo "=== 查看头文件 ==="
          find "${PREFIX}/include" -name "*.h" | head -10 || true
          
          # 创建正确的 whisper.pc 文件（针对Windows修复）
          PC_FILE="${PREFIX}/lib/pkgconfig/whisper.pc"
          mkdir -p "${PREFIX}/lib/pkgconfig"
          
          # 关键修复：创建完整的whisper.pc文件
          cat > "$PC_FILE" << EOF
          prefix=${PREFIX}
          exec_prefix=\${prefix}
          libdir=\${exec_prefix}/lib
          includedir=\${prefix}/include

          Name: whisper
          Description: Port of OpenAI's Whisper model in C/C++
          Version: 1.8.0
          Libs: -L\${libdir} -lwhisper -lggml
          Libs.private: -lm -pthread -lstdc++
          Cflags: -I\${includedir}
          EOF
          
          echo "=== 生成的 whisper.pc 内容 ==="
          cat "$PC_FILE"
          
          echo "=== 验证 whisper.pc 文件格式 ==="
          hexdump -C "$PC_FILE" | head -10 || true

      - name: Configure FFmpeg
        shell: msys2 {0}
        run: |
          cd ffmpeg
          export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
          
          # 验证库文件是否存在
          echo "=== 验证库文件存在性 ==="
          ls -la /usr/local/lib/libwhisper* || echo "whisper库不存在"
          ls -la /usr/local/lib/libggml* || echo "ggml库不存在"
          
          # 调试 pkg-config 设置
          echo "=== 调试 pkg-config ==="
          echo "PKG_CONFIG_PATH: $PKG_CONFIG_PATH"
          ls -la /usr/local/lib/pkgconfig/ || true
          
          # 测试 pkg-config
          echo "=== 测试 pkg-config whisper ==="
          pkg-config --exists whisper && echo "✓ whisper package found" || echo "✗ whisper package not found"
          pkg-config --modversion whisper || echo "无法获取版本"
          pkg-config --cflags whisper || echo "无法获取编译标志"
          pkg-config --libs whisper || echo "无法获取链接标志"
          
          # 测试链接是否工作
          echo "=== 测试链接 ==="
          echo '#include <whisper.h>' > test_whisper.c
          echo 'int main() { return 0; }' >> test_whisper.c
          gcc $(pkg-config --cflags whisper) test_whisper.c $(pkg-config --libs whisper) -o test_whisper && echo "✓ 编译测试成功" || echo "✗ 编译测试失败"
          rm -f test_whisper.c test_whisper
          
          ./configure --disable-everything \
            --enable-static \
            --disable-shared \
            --disable-ffprobe \
            --enable-ffmpeg \
            --enable-avformat \
            --enable-avcodec \
            --enable-avutil \
            --enable-avfilter \
            --enable-swresample \
            --enable-protocol=file \
            --enable-whisper \
            --enable-filter=whisper \
            --enable-decoder=srt \
            --enable-decoder=movtext \
            --enable-decoder=webvtt \
            --enable-decoder=ass \
            --enable-decoder=ssa \
            --enable-decoder=subrip \
            --enable-encoder=srt \
            --enable-encoder=subrip \
            --enable-encoder=movtext \
            --enable-demuxer=mov \
            --enable-demuxer=matroska \
            --enable-demuxer=ass \
            --enable-demuxer=srt \
            --enable-demuxer=webvtt \
            --enable-demuxer=wav \
            --enable-demuxer=mp3 \
            --enable-demuxer=aac \
            --enable-decoder=pcm_s16le \
            --enable-decoder=mp3 \
            --enable-decoder=aac \
            --enable-muxer=srt \
            --pkg-config-flags="--static" \
            --extra-cflags="-I/usr/local/include" \
            --extra-ldflags="-L/usr/local/lib"

      - name: Build and install FFmpeg
        shell: msys2 {0}
        run: |
          cd ffmpeg
          # 获取 CPU 核心数，fallback 到 4
          CORES=$(nproc 2>/dev/null || echo 4)
          echo "使用 $CORES 个核心进行编译"
          make -j$CORES
          make install

      - name: Test FFmpeg functionality
        shell: msys2 {0}
        run: |
          echo "=== 测试 FFmpeg 基本功能 ==="
          /usr/local/bin/ffmpeg.exe -version
          
          echo "=== 测试支持的编解码器 ==="
          /usr/local/bin/ffmpeg.exe -encoders | grep -E "(srt|subrip|movtext)" || echo "没找到字幕编码器"
          /usr/local/bin/ffmpeg.exe -decoders | grep -E "(srt|movtext|webvtt|ass|ssa)" || echo "没找到字幕解码器"
          /usr/local/bin/ffmpeg.exe -decoders | grep -E "(mp3|aac|pcm_s16le)" || echo "没找到音频解码器"
          
          echo "=== 测试支持的格式 ==="
          /usr/local/bin/ffmpeg.exe -formats | grep -E "(mov|matroska|srt|wav|mp3|aac)" || echo "没找到支持的格式"
          
          echo "=== 测试 Whisper 过滤器 ==="
          /usr/local/bin/ffmpeg.exe -hide_banner -filters | grep -i whisper || echo "Whisper 过滤器缺失"

      - name: Copy dependencies
        shell: msys2 {0}
        run: |
          mkdir -p /usr/local/bin/ffmpeg
          cp /usr/local/bin/ffmpeg.exe /usr/local/bin/ffmpeg/
          cp /mingw64/bin/libbz2-1.dll /usr/local/bin/ffmpeg/
          cp /mingw64/bin/libiconv-2.dll /usr/local/bin/ffmpeg/
          cp /mingw64/bin/liblzma-5.dll /usr/local/bin/ffmpeg/
          cp /mingw64/bin/libwinpthread-1.dll /usr/local/bin/ffmpeg/
          cp /mingw64/bin/zlib1.dll /usr/local/bin/ffmpeg/



      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-windows
          path: D:\a\_temp\msys64\usr\local\bin\ffmpeg