name: CI Test

on:
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Set execute permissions on gradlew
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test